// emotionDataset.js
// A massive sample lexicon inspired by the NRC Emotion Lexicon.
// In production, you might load a more comprehensive JSON file from a server or database.

export const emotionLexicon = {
  // JOY
  "happy": { emotion: "joy", score: 1.0 },
  "joyful": { emotion: "joy", score: 1.0 },
  "delighted": { emotion: "joy", score: 1.0 },
  "cheerful": { emotion: "joy", score: 1.0 },
  "content": { emotion: "joy", score: 1.0 },
  "elated": { emotion: "joy", score: 1.0 },
  "ecstatic": { emotion: "joy", score: 1.0 },
  "merry": { emotion: "joy", score: 1.0 },
  "sunny": { emotion: "joy", score: 1.0 },
  "jovial": { emotion: "joy", score: 1.0 },
  "exuberant": { emotion: "joy", score: 1.0 },
  "radiant": { emotion: "joy", score: 1.0 },
  "blissful": { emotion: "joy", score: 1.0 },
  "thrilled": { emotion: "joy", score: 1.0 },
  "gleeful": { emotion: "joy", score: 1.0 },
  "upbeat": { emotion: "joy", score: 1.0 },
  "satisfied": { emotion: "joy", score: 1.0 },
  "optimistic": { emotion: "joy", score: 1.0 },
  "amused": { emotion: "joy", score: 1.0 },
  "jubilant": { emotion: "joy", score: 1.0 },

  // SADNESS
  "sad": { emotion: "sadness", score: 1.0 },
  "depressed": { emotion: "sadness", score: 1.0 },
  "miserable": { emotion: "sadness", score: 1.0 },
  "down": { emotion: "sadness", score: 1.0 },
  "melancholy": { emotion: "sadness", score: 1.0 },
  "gloomy": { emotion: "sadness", score: 1.0 },
  "heartbroken": { emotion: "sadness", score: 1.0 },
  "sorrowful": { emotion: "sadness", score: 1.0 },
  "despairing": { emotion: "sadness", score: 1.0 },
  "forlorn": { emotion: "sadness", score: 1.0 },
  "blue": { emotion: "sadness", score: 1.0 },
  "somber": { emotion: "sadness", score: 1.0 },
  "dejected": { emotion: "sadness", score: 1.0 },
  "grieving": { emotion: "sadness", score: 1.0 },
  "mournful": { emotion: "sadness", score: 1.0 },
  "dismal": { emotion: "sadness", score: 1.0 },
  "woeful": { emotion: "sadness", score: 1.0 },
  "despondent": { emotion: "sadness", score: 1.0 },
  "lamenting": { emotion: "sadness", score: 1.0 },
  "crestfallen": { emotion: "sadness", score: 1.0 },

  // ANGER
  "angry": { emotion: "anger", score: 1.0 },
  "furious": { emotion: "anger", score: 1.0 },
  "irate": { emotion: "anger", score: 1.0 },
  "livid": { emotion: "anger", score: 1.0 },
  "enraged": { emotion: "anger", score: 1.0 },
  "resentful": { emotion: "anger", score: 1.0 },
  "outraged": { emotion: "anger", score: 1.0 },
  "incensed": { emotion: "anger", score: 1.0 },
  "seething": { emotion: "anger", score: 1.0 },
  "annoyed": { emotion: "anger", score: 1.0 },
  "cross": { emotion: "anger", score: 1.0 },
  "exasperated": { emotion: "anger", score: 1.0 },
  "indignant": { emotion: "anger", score: 1.0 },
  "bitter": { emotion: "anger", score: 1.0 },
  "irritable": { emotion: "anger", score: 1.0 },
  "aggravated": { emotion: "anger", score: 1.0 },
  "infuriated": { emotion: "anger", score: 1.0 },
  "choleric": { emotion: "anger", score: 1.0 },
  "wrathful": { emotion: "anger", score: 1.0 },
  "fuming": { emotion: "anger", score: 1.0 },

  // FEAR
  "scared": { emotion: "fear", score: 1.0 },
  "afraid": { emotion: "fear", score: 1.0 },
  "frightened": { emotion: "fear", score: 1.0 },
  "terrified": { emotion: "fear", score: 1.0 },
  "petrified": { emotion: "fear", score: 1.0 },
  "alarmed": { emotion: "fear", score: 1.0 },
  "nervous": { emotion: "fear", score: 1.0 },
  "anxious": { emotion: "fear", score: 1.0 },
  "apprehensive": { emotion: "fear", score: 1.0 },
  "worried": { emotion: "fear", score: 1.0 },
  "horrified": { emotion: "fear", score: 1.0 },
  "panicked": { emotion: "fear", score: 1.0 },
  "intimidated": { emotion: "fear", score: 1.0 },
  "spooked": { emotion: "fear", score: 1.0 },
  "jittery": { emotion: "fear", score: 1.0 },
  "unsettled": { emotion: "fear", score: 1.0 },
  "disturbed": { emotion: "fear", score: 1.0 },
  "trembling": { emotion: "fear", score: 1.0 },
  "scared stiff": { emotion: "fear", score: 1.0 },

  // SURPRISE
  "surprised": { emotion: "surprise", score: 1.0 },
  "shocked": { emotion: "surprise", score: 1.0 },
  "astonished": { emotion: "surprise", score: 1.0 },
  "amazed": { emotion: "surprise", score: 1.0 },
  "stunned": { emotion: "surprise", score: 1.0 },
  "startled": { emotion: "surprise", score: 1.0 },
  "confounded": { emotion: "surprise", score: 1.0 },
  "flabbergasted": { emotion: "surprise", score: 1.0 },
  "dumbfounded": { emotion: "surprise", score: 1.0 },
  "astounded": { emotion: "surprise", score: 1.0 },
  "bewildered": { emotion: "surprise", score: 1.0 },
  "incredulous": { emotion: "surprise", score: 1.0 },
  "taken aback": { emotion: "surprise", score: 1.0 },
  "awe-struck": { emotion: "surprise", score: 1.0 },
  "marveling": { emotion: "surprise", score: 1.0 },

  // LOVE
  "loved": { emotion: "love", score: 1.0 },
  "adored": { emotion: "love", score: 1.0 },
  "cherished": { emotion: "love", score: 1.0 },
  "affectionate": { emotion: "love", score: 1.0 },
  "caring": { emotion: "love", score: 1.0 },
  "devoted": { emotion: "love", score: 1.0 },
  "passionate": { emotion: "love", score: 1.0 },
  "fond": { emotion: "love", score: 1.0 },
  "infatuated": { emotion: "love", score: 1.0 },
  "romantic": { emotion: "love", score: 1.0 },
  "enamored": { emotion: "love", score: 1.0 },
  "tender": { emotion: "love", score: 1.0 },
  "doting": { emotion: "love", score: 1.0 },
  "smitten": { emotion: "love", score: 1.0 },
  "warm": { emotion: "love", score: 1.0 },
  "heartfelt": { emotion: "love", score: 1.0 },

  // DISGUST
  "disgusted": { emotion: "disgust", score: 1.0 },
  "repulsed": { emotion: "disgust", score: 1.0 },
  "revolted": { emotion: "disgust", score: 1.0 },
  "sickened": { emotion: "disgust", score: 1.0 },
  "nauseated": { emotion: "disgust", score: 1.0 },
  "distasteful": { emotion: "disgust", score: 1.0 },
  "abhorrent": { emotion: "disgust", score: 1.0 },
  "loathsome": { emotion: "disgust", score: 1.0 },
  "repellent": { emotion: "disgust", score: 1.0 },
  "offensive": { emotion: "disgust", score: 1.0 },
  "vile": { emotion: "disgust", score: 1.0 },
  "gross": { emotion: "disgust", score: 1.0 },
  "detestable": { emotion: "disgust", score: 1.0 },
  "repugnant": { emotion: "disgust", score: 1.0 },
  "nauseating": { emotion: "disgust", score: 1.0 },
  "icky": { emotion: "disgust", score: 1.0 },

  // ANXIETY (Additional words for fear and nervousness can also go here)
  "anxious": { emotion: "anxiety", score: 1.0 },
  "worried": { emotion: "anxiety", score: 1.0 },
  "apprehensive": { emotion: "anxiety", score: 1.0 },
  "tense": { emotion: "anxiety", score: 1.0 },
  "jittery": { emotion: "anxiety", score: 1.0 },
  "restless": { emotion: "anxiety", score: 1.0 },
  "uneasy": { emotion: "anxiety", score: 1.0 },
  "fretful": { emotion: "anxiety", score: 1.0 },
  "agitated": { emotion: "anxiety", score: 1.0 },
  "panicky": { emotion: "anxiety", score: 1.0 },
  "disturbed": { emotion: "anxiety", score: 1.0 },
  "disquieted": { emotion: "anxiety", score: 1.0 },
  "alarmed": { emotion: "anxiety", score: 1.0 },
  "perturbed": { emotion: "anxiety", score: 1.0 },
  "on edge": { emotion: "anxiety", score: 1.0 },
  "uptight": { emotion: "anxiety", score: 1.0 },
  "edgy": { emotion: "anxiety", score: 1.0 }
};
